### ISSUE TITLE
Fix spacing, font size and font weight, etc. of top left main navigation

### ISSUE THREAD

**Issue by lilygdu** [lilygdu/TH-starter#1]
Match the expected: 
<img width="396" alt="Screen Shot 2021-02-04 at 10 16 58 AM" src="https://user-images.githubusercontent.com/77121299/106913661-13141c00-66b9-11eb-9f7c-dd391de84164.png">

Current: 
<img width="399" alt="Screen Shot 2021-02-04 at 10 17 02 AM" src="https://user-images.githubusercontent.com/77121299/106913691-1effde00-66b9-11eb-9afc-904dbbc44886.png">

Changes include: 

- [ ] Matching font size and weight 
- [x] Creating more spacing between words 
- [x] Add downward carrot next to "More" 
- [x] Adjust height of navigation 
- [x] Add hover to all links to appear as underlines

**Comment by andyweiss1982** [comment]
closed via #2
