### ISSUE TITLE
Favicon and Document Title

### ISSUE THREAD

**Issue by andyweiss1982** [lilygdu/TH-starter#100]
We are missing the maple leaf, and we can use Helmet to change the document title for each page: 
https://www.npmjs.com/package/react-helmet

**Comment by andyweiss1982** [comment]
This is a working example, @lilygdu and @ebugbey can pick up where I left off with the other page titles

https://github.com/lilygdu/TH-starter/pull/118/files#diff-9ff0b7a1a220ddedfbb8ce5d83f5691a78f1675e1e6b59302c83b51a7ff93dccR110

**Comment by lilygdu** [comment]
points: 3
