### ISSUE TITLE
Sign up button loading animation

### ISSUE THREAD

**Issue by lilygdu** [lilygdu/TH-starter#112]
Add animation for when sign up button is clicked on the sign up page

**Comment by andyweiss1982** [comment]
This is how we implement it on the sign in page:

https://github.com/lilygdu/TH-starter/blob/eaacb64f29ea302687518674e3621442a0255b59/public/pages/SignIn.js#L58

https://github.com/lilygdu/TH-starter/blob/eaacb64f29ea302687518674e3621442a0255b59/public/pages/SignIn.js#L61-L63

https://github.com/lilygdu/TH-starter/blob/eaacb64f29ea302687518674e3621442a0255b59/public/pages/SignIn.js#L96-L102

**Comment by lilygdu** [comment]
points: 2
