### ISSUE TITLE
Add Recent Orders Component to Recent Orders Page

### ISSUE THREAD

**Issue by ghost** [lilygdu/TH-starter#115]
Add the recent orders section to the recent orders page to display the recent orders
WHERE the refresh button will re-execute the query

- [x] order number needs to display (can this be a reusable function)
- [x] format time
- [x] name of first item
- [x] buttons should be same width
- [x] spacing, fonts, colors
- [x] spacing _between_ orders
- [ ] refresh?

![Screen Shot 2021-03-12 at 1 57 41 PM](https://user-images.githubusercontent.com/77121299/111173058-96037e80-8563-11eb-962f-cfbcc0a0cb7b.png)

With no orders, display as below, with the Start Order button redirecting to the main menu:
![Screen Shot 2021-03-15 at 10 52 06 AM](https://user-images.githubusercontent.com/77121299/111172841-65bbe000-8563-11eb-9b99-1ce65df2330d.png)

**Comment by lilygdu** [comment]
points: 5 

recent items has already been added
