### ISSUE TITLE
Click Tracking

### ISSUE THREAD

**Issue by andyweiss1982** [lilygdu/TH-starter#120]
When a page loads, create and start a session 
- is a page reload a new session or does that extend the existing session? (might be tough)

PURCHASING 

- purchase process: 
1. searching for items 
2. adding items to cart / removing items from cart
3. check out / confirm purchase
4. completing purchase at checkout (stripe ID)
- cart abandonment 
- Session creation
- Page navigation events 
- Track click events

OPTIMIZING: SPEED 
- user journey from start to finish (sessions using the timestamps of the user) 
- click events  
- page load vs. data load (track the dip in speed over time) 

OPTIMIZING: UX 
- integrate the signed in user vs. non-signed in user > what do we care about? 
- what are the hot spots on the screen (where to place the high priority categories / items)
- page navigation events (going backwards from a page) 
- geolocation (* TBD) 

VIEW   EVENT TABLE |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
id | page_visit_id | element_type | element_id | tracking_id | viewed_at | view_x | view_y
primary key | foreign key | either category or item | sanity id of corresponding item | unique id given to specific items | timestamp of view | % of x | % of y

- This table will track location and time of when specific items on the page were viewed by the user. Will be used to gain further insight into user interaction with elements (i.e. which elements were seen by the user but not further interacted with)

CLICK   EVENTS TABLE |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
id | page_visit_id | clicked_at | tracking_id | click_event_type | click_x | click_y
primary key | foreign key | timestamp of click  | what was clicked | i.e., add to order | adjust for window size | adjust for window size
- This table will track location and time of when specific items on the page were clicked by the user. Will be used to gain further insight into user interaction with elements (i.e. travel path of user clicks as they navigate the app)

**Click event types to track:**
1. add to order
2. remove from cart
3. checkout cart
4. confirm payment
5. increment/decrement quantity of items
6. open/close of modals (signout, view receipt details, etc.)
7. 

**Tracking_ids:**
1. reorder button
2. link clicks
3. :)

**Business Proposition:**

We want to know what elements users are clicking on, in what order, on what parts of the page, so that we can convert more users to purchases.

But we can't use a third party library for this, it's too expensive!

**Technical Considerations**

We are probably going to want to record each click in a table in our SQL database.  

So we should probably think pretty hard about what information we really have access to.

What element was clicked - Can we tag all meaningful elements that we care about in some way?
What area of the page was clicked?  Can we get this information from the click event?
What time did the click happen?  How long was the user on the page when it happened?  
Is there some way to logically group a series of related clicks together into a session to build a picture of the actions a given user took?
Who made each click?  Is there something we can do to uniquely identify users who are not currently logged in?

It might be helpful to think of what SQL queries we might _want_ to be able to write, and then try to design the feature around that goal.

**Comment by lilygdu** [comment]
points: 13
