### ISSUE TITLE
Main Menu button 

### ISSUE THREAD

**Issue by lilygdu** [lilygdu/TH-starter#121]
Main Menu Button can be improved now that we have more ability to override button styles

**Comment by lilygdu** [comment]
points: 2

**Comment by andyweiss1982** [comment]
We did this before we had the ability to override styles on the `Button` component.

Here are some examples that work now:

https://github.com/lilygdu/TH-starter/blob/22bc5e8c7486fcc8a1a078810c67bb91631f2e12/public/components/Cart.js#L68-L73

https://github.com/lilygdu/TH-starter/blob/22bc5e8c7486fcc8a1a078810c67bb91631f2e12/public/components/RecentOrder.js#L111-L116

Try to make the styles closer match the actual site!
