### ISSUE TITLE
Hide "Not Your Computer" text on smaller screens

### ISSUE THREAD

**Issue by andyweiss1982** [lilygdu/TH-starter#15]

**Comment by ghost** [comment]
GIVEN a user is on the sign-up page, not full screen width
WHEN the screen hits max-width of 815 px (when the footer and top nav bar display: none
THEN the 'Not your computer?...' text should also display: none

Expected progression of events:
![Screen Shot 2021-02-05 at 10 28 48 AM](https://user-images.githubusercontent.com/77162982/107054027-97d86600-679d-11eb-9e47-71af7c5a3662.png)
![Screen Shot 2021-02-05 at 10 29 46 AM](https://user-images.githubusercontent.com/77162982/107054042-9ad35680-679d-11eb-8d16-36772bfefd67.png)
