### ISSUE TITLE
Adjust label sizing on items to account for items with longer names

### ISSUE THREAD

**Issue by ghost** [lilygdu/TH-starter#154]
When the screen is not full-width, items with longer names have the labels cut off:

![image](https://user-images.githubusercontent.com/77162982/111698651-72fbf780-880d-11eb-9440-880585e86fca.png)

I believe this can be achieved by increasing the grid-template-columns min width. When the columns changes from 4 to 3, the labels go back to looking fine

AC:
- [ ] all labels for all items are not cut off at any screen size 😛

**Comment by andyweiss1982** [comment]
My two cents: Let's just remove the words "2020 Everyday Collection" in sanity
