### ISSUE TITLE
Some images still getting blurred image in background

### ISSUE THREAD

**Issue by ghost** [lilygdu/TH-starter#155]
Only seeing this issue on the below two items:

![image](https://user-images.githubusercontent.com/77162982/111699181-2b29a000-880e-11eb-88e0-fd3581a7f2a4.png)

![image](https://user-images.githubusercontent.com/77162982/111699378-6a57f100-880e-11eb-9848-2fa6b60826b8.png)

**Comment by lilygdu** [comment]
Plain Bagel too
![Uploading Screen Shot 2021-03-19 at 12.35.40 AM.png…]()

**Comment by andyweiss1982** [comment]
Oh so the blurup background images are not properly disappearing?  Assign this one to me!
