### ISSUE TITLE
Did we intend for View Receipt on order confirmation to pop open anything?

### ISSUE THREAD

**Issue by ghost** [lilygdu/TH-starter#158]
I feel like this could show the same thing as the order details on the recent orders page

![image](https://user-images.githubusercontent.com/77162982/111699984-2fa28880-880f-11eb-8aec-8703ad511d8c.png)

**Comment by andyweiss1982** [comment]
Agreed!

**Comment by andyweiss1982** [comment]
Juice not worth the squeeze, WONT DO for now
