### ISSUE TITLE
More long item-name issues

### ISSUE THREAD

**Issue by ghost** [lilygdu/TH-starter#160]
In order confirmation screen:
![image](https://user-images.githubusercontent.com/77162982/111700428-c66f4500-880f-11eb-958f-9c31d71d6b89.png)

In cart:
![image](https://user-images.githubusercontent.com/77162982/111700564-f3235c80-880f-11eb-8ec0-b8511c6c4860.png)

Perhaps adding some gap or padding or what not to make it so these item names are butting right up against the adjacent column would look better

**Comment by andyweiss1982** [comment]
Yes to gap or padding but only on the seam between the two elements
