### ISSUE TITLE
Make adjustments to top right of header: login and shopping cart elements

### ISSUE THREAD

**Issue by ghost** [lilygdu/TH-starter#3]
Current state:
![Screen Shot 2021-02-04 at 10 50 42 AM](https://user-images.githubusercontent.com/77162982/106918076-e111b280-66d6-11eb-981f-5511665ac593.png)

Please add the shopping cart button next to the login:
![Screen Shot 2021-02-04 at 10 49 42 AM](https://user-images.githubusercontent.com/77162982/106918222-00a8db00-66d7-11eb-9def-07df954d3489.png)

Both the login and shopping cart buttons should receive their corresponding hover background color change AND the pointer cursor:
Login - translucent white
![Screen Shot 2021-02-04 at 10 49 55 AM](https://user-images.githubusercontent.com/77162982/106918363-20d89a00-66d7-11eb-9ef6-748496fd2188.png)

Shopping cart - translucent black
![Screen Shot 2021-02-04 at 10 50 02 AM](https://user-images.githubusercontent.com/77162982/106918452-36e65a80-66d7-11eb-9bfe-858c22a78579.png)

**Comment by andyweiss1982** [comment]
closed via #4
