### ISSUE TITLE
Sign Up Form Errors

### ISSUE THREAD

**Issue by lilygdu** [lilygdu/TH-starter#85]
There are 4 different types of fields in our form (select, text input, email input, checkbox).
Some of them are required others are optional
_The fields all behave differently, based on whether or not the form has already been submitted_

**1. Country Select**
GIVEN a user is selecting their country
WHEN they do not change the selection from the default (Canada)
THEN Canada should be stored as their country in the data

WHEN they select either USA or Canada
THEN the country they’ve selected should be stored as their country in the data
IF the user were to change one of the country options in the Inspect elements
THEN the country should default to the country whose language their browser is defaulting to

**2. Email Address Input** 

GIVEN a user has clicked into the email input field
WHEN they blur off the field without typing anything
THEN they should receive the ‘Email is a required field’ error message

GIVEN the user has not filled out the email input field
WHEN they try to submit the form
THEN they should receive the ‘Email is a required field’ error message

GIVEN the user has received an ‘Email is a required field’ error message
WHEN they start typing in their email
THEN they input should validate after every change (until they type an email that follows the correct email Regex, the input field will stay invalid and show the ‘That doesn’t look like a valid email’ error message

GIVEN the user has typed in their email
WHEN the email matches the Regex format
THEN the input should immediately validate (turn green with check mark)
![Invalid Email](https://user-images.githubusercontent.com/77121299/110487636-9fdc3c00-80a2-11eb-9254-68be0e643482.png)

https://user-images.githubusercontent.com/77121299/110487646-a1a5ff80-80a2-11eb-983d-8093c8399660.mov

An existing user is attempting to sign up: 

GIVEN the user has typed in an email of an existing account
WHEN they submit the form
THEN they should receive a ‘An account with the given email already exists’ error message

GIVEN they’ve received this error message
WHEN they make any change to the email or click into the form somewhere else
THEN they will need to submit the form again until it re-validates

https://user-images.githubusercontent.com/77121299/110489173-06ae2500-80a4-11eb-8d6b-e91f305658f4.mov

**3. Name Input**
GIVEN the user is on the sign up page
WHEN the name input is left blank and the user clicks EITHER the sign up button or the user clicks anywhere else on the window 
THEN the invalid state displays with the error message "Name is a required field." 

GIVEN the user is on the sign up page and the invalid state is displayed
WHEN the user begins typing a name (> 1 character) 
THEN the name should be displayed in a valid state (green border and green checkmark) 

https://user-images.githubusercontent.com/77121299/110487903-de71f680-80a2-11eb-9b8e-aa47851d45e1.mov

https://user-images.githubusercontent.com/77121299/110487919-e29e1400-80a2-11eb-916e-cec6dd349fb2.mov

**4. Promotional emails / special offers check box (optional / not required)** 
GIVEN the user is on the sign up page
WHEN the user checks or does not check this box
THEN submit the form 

**5. Terms of Service (TOS) check box** 
GIVEN the user is on the sign up page the TOS consent is not checked (showing default state) 
WHEN the user clicks the sign up button
THEN display invalid state and the error message "You must agree to the privacy policy and terms of service before signing up."

WHEN the TOS consent IS checked and the user clicks the sign up button
THEN remove the invalid state and submit the form 

https://user-images.githubusercontent.com/77121299/110487945-e762c800-80a2-11eb-96d8-517a20a6c593.mov

Some of them have multiple reasons they could potentially be invalid (hello, email?)
Some of them need to interact with the server before we can know if they are valid (does this account already exist?)
Some of them can show in default, valid or invalid states, others only show an error or default state, others just show a default state.
Then, add some User Stories that explain the use cases for these acceptance criteria.

**Comment by ghost** [comment]
Only issues I see is that our email address error says:
![image](https://user-images.githubusercontent.com/77162982/110697424-554de300-81ba-11eb-8354-445648e6971f.png)

What we're expecting:
![image](https://user-images.githubusercontent.com/77162982/110697404-4ebf6b80-81ba-11eb-87d9-3a22fd397ccc.png)

**Comment by lilygdu** [comment]
closed via #86
