### ISSUE TITLE
Menu Item Spacing

### ISSUE THREAD

**Issue by andyweiss1982** [lilygdu/TH-starter#99]
We can do better
 
- [ ] Ensure all item names fit (i.e., merchandise names)
- [ ]  Set columns to 3 (to match real site)

Expected:

![Screen Shot 2021-03-11 at 9 07 05 AM](https://user-images.githubusercontent.com/8116130/110799546-45311480-8249-11eb-939c-67cce5098a2b.png)

Actual:

![Screen Shot 2021-03-11 at 9 07 39 AM](https://user-images.githubusercontent.com/8116130/110799529-406c6080-8249-11eb-8afa-10032fd0dd40.png)

**Comment by lilygdu** [comment]
points: 2
